CREATE TABLE employee (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    name VARCHAR(100),
    phone VARCHAR(100),
    address VARCHAR(100),
    username VARCHAR(100) NOT NULL UNIQUE, 
    password VARCHAR(100)
);

CREATE TABLE tables (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    status INT NOT NULL
);

CREATE TABLE manager (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    name VARCHAR(100),
    phone VARCHAR(100),
    address VARCHAR(100),
    username VARCHAR(100) NOT NULL UNIQUE, 
    password VARCHAR(100)
);

CREATE TABLE drink (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    price INT NOT NULL
);

ALTER TABLE tables ADD COLUMN billId INT;

CREATE TABLE bill (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    createdDate DATE NOT NULL
);

